local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>tpf', builtin.find_files, {})
vim.keymap.set('n', '<leader>tgf', builtin.git_files, {})
vim.keymap.set('n', '<leader>tps', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end)
