return {}
-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     setup = {
--       tsserver = {
--         require("lazyvim.util").lsp.on_attach(function(client)
--           if client.name == "tsserver" then
--             client.server_capabilities.documentFormattingProvider = false
--           end
--         end),
--       },
--     },
--   },
-- }
